### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by jmalab1** [jpugs1527/COSC617-Group-Project#2]
Create a page to allow user to register
- require personal information including drivers license
- we will have to "fake" validation on the driver's license (just have to go with expiration date to determine whether or not they can rent)
- same for insurance

**Comment by jmalab1** [comment]
we only need to ask the 2nd and 3rd bullet if the user decides to rent.

**Comment by DrValkaryon** [comment]
I'm trying to figure out what's handling validation in our stack. Are we doing this ourselves with the backend database or are we using an external tokenizer like okta?

**Comment by jmalab1** [comment]
> I'm trying to figure out what's handling validation in our stack. Are we doing this ourselves with the backend database or are we using an external tokenizer like okta?

I have it set to use jwtwebtoken.. when a user logs in, it saves the token to localStorage and the user object. We need to add logic to refresh the token if the user is actively using the site.. The token expires in 30 minutes..
